In [4]:
import json
import pandas as pd
import requests 

url = "https://apis.datos.gob.ar/georef/api/provincias?campos=id,nombre"

response = requests.get(url)

#verificacion

if response.status_code == 200:
    print(response.json())
else: 
    print(f"Error: {response.status_code}")

{'cantidad': 24, 'inicio': 0, 'parametros': {'campos': ['id', 'nombre']}, 'provincias': [{'id': '54', 'nombre': 'Misiones'}, {'id': '74', 'nombre': 'San Luis'}, {'id': '70', 'nombre': 'San Juan'}, {'id': '30', 'nombre': 'Entre Ríos'}, {'id': '78', 'nombre': 'Santa Cruz'}, {'id': '62', 'nombre': 'Río Negro'}, {'id': '26', 'nombre': 'Chubut'}, {'id': '14', 'nombre': 'Córdoba'}, {'id': '50', 'nombre': 'Mendoza'}, {'id': '46', 'nombre': 'La Rioja'}, {'id': '10', 'nombre': 'Catamarca'}, {'id': '42', 'nombre': 'La Pampa'}, {'id': '86', 'nombre': 'Santiago del Estero'}, {'id': '18', 'nombre': 'Corrientes'}, {'id': '82', 'nombre': 'Santa Fe'}, {'id': '90', 'nombre': 'Tucumán'}, {'id': '58', 'nombre': 'Neuquén'}, {'id': '66', 'nombre': 'Salta'}, {'id': '22', 'nombre': 'Chaco'}, {'id': '34', 'nombre': 'Formosa'}, {'id': '38', 'nombre': 'Jujuy'}, {'id': '02', 'nombre': 'Ciudad Autónoma de Buenos Aires'}, {'id': '06', 'nombre': 'Buenos Aires'}, {'id': '94', 'nombre': 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'}], 'total': 24}

In [13]:
data = json.loads(response.text)
provincias_df = pd.json_normalize(data['provincias'])

provincias_df

    id                                             nombre
0   54                                           Misiones
1   74                                           San Luis
2   70                                           San Juan
3   30                                         Entre Ríos
4   78                                         Santa Cruz
5   62                                          Río Negro
6   26                                             Chubut
7   14                                            Córdoba
8   50                                            Mendoza
9   46                                           La Rioja
10  10                                          Catamarca
11  42                                           La Pampa
12  86                                Santiago del Estero
13  18                                         Corrientes
14  82                                           Santa Fe
15  90                                            Tucumán
16  58                                            Neuquén
17  66                                              Salta
18  22                                              Chaco
19  34                                            Formosa
20  38                                              Jujuy
21  02                    Ciudad Autónoma de Buenos Aires
22  06                                       Buenos Aires
23  94  Tierra del Fuego, Antártida e Islas del Atlánt...